### ISSUE TITLE
Map Widget - Delete Layers

### ISSUE THREAD

**Issue by geoportal2x** [geoportal2x/gwp#14]
On the Map Widget,
users shall be provided with the possibility to delete one or more  layers
 appearing within the Layer Manger window.
The screen shot below highlight the componets involved and a proposed appraoch

![mapwidget-deletelayer](https://f.cloud.github.com/assets/6065935/1653511/9c9a1e7a-5b36-11e3-8800-960f3f6d4819.png)

**Comment by ntrocino** [comment]
There is now the possibility to delete layers from layer switcher component. Still graphical elements to be improved
